"""Regenerate lethe/static/demo.json, the recorded conversation behind the UI's "Watch a 30-second demo".

Run from anywhere, with the project installed (pip install -e .):

    python scripts/make_demo.py

No API key needed: only the LLM is scripted. Everything else is lethe's real pipeline (AgentMemory,
the retention policy, FastEmbed embeddings, extraction batching, eviction and reload), so the
scores, the fact that sinks and the fact that comes back are what lethe actually does. Rerun it
after changing the policy, the extraction flow or the /memories and /ops shapes, since the page
replays these snapshots through the same code that renders a live chat.

The script fails if the replay no longer shows a fact being archived and then brought back.
"""

import asyncio
import json
import sys
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from lethe import AgentMemory, PolicyConfig, Store  # noqa: E402
from lethe.agent import MemoryAgent  # noqa: E402
from lethe.extract import FactExtractor  # noqa: E402
from lethe.index import FastEmbedder, VectorIndex  # noqa: E402

OUT = ROOT / "lethe" / "static" / "demo.json"
BUDGET, GRACE = 3, 2  # small, so a fact sinks within a few turns

# (user message, scripted reply, facts the scripted extractor pulls from it; None for a question)
SCRIPT = [
    ("hi! my sister meera lives in kochi", "Nice to meet you. Kochi sounds lovely, do you visit her often?", ["My sister Meera lives in Kochi."]),
    ("lol not really", "Fair enough. What else is going on with you?", []),
    ("i play football every sunday", "Sunday football is a great habit. Which position do you play?", ["I play football every Sunday."]),
    ("i work as a nurse at city hospital", "That's demanding work. Thanks for what you do.", ["I work as a nurse at City Hospital."]),
    ("my dog is called biscuit", "Biscuit is a great name for a dog.", ["My dog is called Biscuit."]),
    ("the weather is nice today", "Enjoy it while it lasts!", []),
    ("where does my sister live?", "Your sister Meera lives in Kochi.", None),
]
FACTS = {msg: facts for msg, _, facts in SCRIPT if facts is not None}
REPLIES = {msg: reply for msg, reply, _ in SCRIPT}


class ScriptedLLM:
    """Plays both roles: the fact extractor (by prompt text) and the chat model (by user message)."""

    model = "scripted demo"

    async def chat(self, messages):
        prompt = messages[-1]["content"]
        if "extract durable personal facts" in prompt:
            out = []
            for line in prompt.splitlines():
                if line.startswith("[t"):
                    turn, text = line[2:].split("] ", 1)
                    out += [{"turn": int(turn), "fact": f} for f in FACTS.get(text, [])]
            return json.dumps({"facts": out})
        return REPLIES[prompt]


async def record() -> dict:
    mem = AgentMemory(
        Store(":memory:"), VectorIndex(None, f"demo-{uuid.uuid4().hex[:8]}"), FastEmbedder(),
        PolicyConfig(active_budget=BUDGET, grace_turns=GRACE),
    )
    llm = ScriptedLLM()
    agent = MemoryAgent(mem, llm, extractor=FactExtractor(llm))
    sid, steps = "demo", []
    for msg, _, _ in SCRIPT:
        reply = await agent.chat(sid, msg)
        reply.pop("prompt_tokens", None)
        reply["pending"] = len(agent.pending.get(sid, []))  # what the API adds to each chat response
        ops = [{k: v for k, v in o.items() if k != "ts"} for o in mem.store.ops(sid, 40)]
        steps.append({"user": msg, "reply": reply, "memories": mem.snapshot(sid), "ops": ops})
    return {
        "about": "Scripted replay generated by running lethe's real memory pipeline with a scripted LLM. No API calls.",
        "budget": BUDGET,
        "steps": steps,
    }


def main():
    demo = asyncio.run(record())
    final_ops = {o["op"] for o in demo["steps"][-1]["ops"]}
    if not {"evict", "reload"} <= final_ops:
        sys.exit(f"The replay no longer shows a fact sinking and coming back (ops: {sorted(final_ops)}). "
                 "Adjust SCRIPT, BUDGET or GRACE; demo.json was not written.")
    OUT.write_text(json.dumps(demo, indent=1) + "\n", encoding="utf-8")
    texts = {m["id"]: m["text"] for s in demo["steps"] for m in s["memories"]}
    for i, s in enumerate(demo["steps"], 1):
        moves = [f"{o['op']} {texts.get(o['memory_id'], '?')!r}" for o in s["ops"] if o["turn"] == i and o["op"] in ("evict", "reload")]
        print(f"turn {i}: {s['user']}" + (f"  ->  {'; '.join(moves)}" if moves else ""))
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
